name: CI/CD Pipeline

on: [push]

jobs:
  full_check:
    name: Full Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt install libopenmpi-dev
          sudo apt install gpaw
          pip install -r requirements.txt
      - name: Format Check
        run: |
          black --check src/
          black --check auxiliary/
      - name: Type Check
        run: |
          mypy src/
          mypy auxiliary/
      - name: Code Style Check
        run: |
          pylint src/
          pylint auxiliary/
      - name: Test
        run: |
          mkdir -p reports/pytest/html
          pytest --cov=src --cov-config=setup.cfg --cov-branch --cov-report=html:reports/pytest/html --cov-report=term test
      - name: Upload pytest reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: reports/pytest
